# Generated by Django 4.2 on 2023-10-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmodels',
            name='label',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
