# Generated by Django 4.2.1 on 2023-09-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_profile_work_of_interest'),
        ('token_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodels',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_profile', to='profiles.profile'),
        ),
    ]
